kind: Service 
apiVersion: v1
metadata:
  name: landingpage-staging
  namespace: staging
spec:
  selector: 
    app: landingpage
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80 
    nodePort: 30090
  type: LoadBalancer